version: "3.8"

services:

  whiteboard:
    image: rofl256/whiteboard:latest
    container_name: whiteboard
    ports:
    - 40001:8080

  netbootxyz:
    image: linuxserver/netbootxyz:latest
    container_name: netbootxyz
    volumes:
    - ~/data/netbootxyz/config/menus/local:/config/menus/local
    ports:
    - 40002:3000
    - 69:69/udp
    - 40003:80

  dashmachine:
    image: rmountjoy/dashmachine:latest
    container_name: dashmachine
    volumes:
    - ./config.ini:/dashmachine/dashmachine/user_data/config.ini
    ports:
    - 5000:5000

    #  shinobi:
    #    image: shinobisystems/shinobi:latest-ubuntu
    #    container_name: shinobi
    #    environment: [APP_BRANCH=dev]
    #    ports: [8080:8080]
    #    volumes: [/dev/shm/shinobiStreams:/dev/shm/streams,../../../../data/shinobi/shinobiConfig:/config,../../../../data/shinobi/shinobiCustomAutoLoad:/customAutoLoad,../../../../data/shinobi/shinobiDatabase:/var/lib/mysql,../../../../data/shinobi/shinobiVideos:/opt/shinobi/videos]

  mumble:
    image: phlak/mumble:latest
    container_name: mumble
    ports:
    - 64738:64738
    - 64738:64738/udp

  ssh:
    image: linuxserver/openssh-server:latest
    container_name: ssh
    environment:
    - PASSWORD_ACCESS=true
    - USER_PASSWORD=debian
    - USER_NAME=debian
    ports:
    - 2222:2222
    volumes:
    - ~/mnt:/mnt/data
    - ~/foo:/mnt/foo

  wordpress:
    image: wordpress:latest
    ports:
    - 80:80
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
    - ~/data/wordpress:/var/www/html
    depends_on: [wordpress-db]

  wordpress-db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
    - ~/data/db:/var/lib/mysql

  bitwarden:
    image: bitwardenrs/server:latest
    volumes:
    - ~/data/bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups
    ports:
    - 80:80

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
    - 1234:80

  openvas:
    image: mikesplain/openvas:latest
    container_name: openvas
    ports:
      - 443:443

  searx:
    image: searx/searx:latest
    container_name: searx
    ports:
        - 8080:8080
