version: "3.8"

services:

  whiteboard:
    image: rofl256/whiteboard:version-1.6
    container_name: whiteboard
    ports:
    - 40001:8080

  netbootxyz:
    image: linuxserver/netbootxyz:version-0.6.4
    container_name: netbootxyz
    volumes:
    - ~/data/netbootxyz/config/menus/local:/config/menus/local
    ports:
    - 40002:3000
    - 69:69/udp
    - 40003:80

  dashmachine:
    image: rmountjoy/dashmachine:v0.5-4
    container_name: dashmachine
    volumes:
    - ./config.ini:/dashmachine/dashmachine/user_data/config.ini
    ports:
    - 5000:5000

    #  shinobi:
    #    image: shinobisystems/shinobi:latest-ubuntu
    #    container_name: shinobi
    #    environment: [APP_BRANCH=dev]
    #    ports: [8080:8080]
    #    volumes: [/dev/shm/shinobiStreams:/dev/shm/streams,../../../../data/shinobi/shinobiConfig:/config,../../../../data/shinobi/shinobiCustomAutoLoad:/customAutoLoad,../../../../data/shinobi/shinobiDatabase:/var/lib/mysql,../../../../data/shinobi/shinobiVideos:/opt/shinobi/videos]

  mumble:
    image: phlak/mumble:1.3.4
    container_name: mumble
    ports:
    - 64738:64738
    - 64738:64738/udp

  ssh:
    image: linuxserver/openssh-server:8.4_p1-r3-ls43
    container_name: ssh
    environment:
    - PASSWORD_ACCESS=true
    - USER_PASSWORD=debian
    - USER_NAME=debian
    ports:
    - 2222:2222
    volumes:
    - ~/mnt:/mnt/data
    - ~/foo:/mnt/foo

  wordpress:
    image: wordpress:5.7.2
    ports:
    - 80:80
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
    - ~/data/wordpress:/var/www/html
    depends_on: [wordpress-db]

  wordpress-db:
    image: mariadb:10.6.1
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
    - ~/data/wordpressdb:/var/lib/mysql

  bitwarden:
    image: vaultwarden/server:1.21.0
    volumes:
    - ~/data/bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups
    ports:
    - 80:80

  pgadmin:
    image: dpage/pgadmin4:5.1
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
    - 1234:80

  openvas:
    image: mikesplain/openvas:9
    container_name: openvas
    ports:
      - 443:443

  searx:
    image: searx/searx:latest
    container_name: searx
    ports:
        - 8080:8080

  test-proxy:
    image: nginx:1.21.0-alpine
    container_name: test-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./searx.example.com.pem:/etc/nginx/searx.example.com.crt
      - ./searx.example.com-key.pem:/etc/nginx/searx.example.com-key.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - searx

  pihole:
    container_name: pihole
    image: pihole/pihole:v5.8.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      #volumes:
      #  - './etc-pihole/:/etc/pihole/'
      #  - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
    - 127.0.0.1
    - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
