version: "3.7"

services:

  whiteboard:
    image: rofl256/whiteboard
    container_name: whiteboard
    ports: [40001:8080]

  netbootxyz:
    image: linuxserver/netbootxyz
    container_name: netbootxyz
    environment: [PUID=1000,PGID=1000,MENU_VERSION=1.9.9]
    volumes: [../data/netbootxyz/config:/config]
    ports: [40002:3000,69:69/udp,40003:80]

  dashmachine:
    image: rmountjoy/dashmachine
    container_name: dashmachine
    volumes: [./config.ini:/dashmachine/dashmachine/user_data/config.ini]
    ports: [5000:5000]

  shinobi:
    image: shinobisystems/shinobi:latest-ubuntu
    container_name: shinobi
    environment: [APP_BRANCH=dev]
    ports: [8080:8080/tcp]
    volumes: [/dev/shm/shinobiStreams:/dev/shm/streams,../data/shinobi/shinobiConfig:/config,../data/shinobi/shinobiCustomAutoLoad:/customAutoLoad,../data/shinobi/shinobiDatabase:/var/lib/mysql,../data/shinobi/shinobiVideos:/opt/shinobi/videos]
