# to run: docker-compose run
#
# Create a .env file in the same folder as this file and change the variables.
# MOUNT_POINT=/tmp/
# VPN_USERNAME=changeme
# VPN_PASSWORD=changeme
#
#
version: "2"

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/tmp/transmission/data/:/data
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/24

  proxy:
   image: haugene/transmission-openvpn-proxy
   links:
     - transmission
   ports:
     - 8080:8080
   volumes:
     - /etc/localtime:/etc/localtime:ro

  rss:
   image: haugene/transmission-rss
   links:
     - transmission
   environment:
     - RSS_URL=http://.../xxxxx.rss

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /var/tmp/sonarr/config:/config
      - /var/tmp/sonarr/tvseries:/tv
      - /var/tmp/sonarr/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /var/tmp/radarr/config:/config
      - /var/tmp/radarr/movies:/movies
      - /var/tmp/radarr/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /var/tmp/jackett/config:/config
      - /var/tmp/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=<timezone>
      - PLEX_CLAIM=<claimToken>
    network_mode: host
    volumes:
      - /var/tmp/plex/config:/config
      - /var/tmp/plex/transcode:/transcode
      - /var/tmp/plex/data:/data
      - /mnt/videos:/videos
