version: "3.8"

services:

  influxdb:
    image: influxdb:1.8.4
    container_name: influxdb
    ports:
    - 8086:8086
    environment:
    - INFLUXDB_REPORTING_DISABLED=false

  #telegraf:
  #  image: telegraf:latest
  #  container_name: telegraf
  #  depends_on: [influxdb]
  #  volumes:
  #  - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #  - /var/run/docker.sock:/var/run/docker.sock

  grafana:
    image: grafana/grafana:7.5.1
    container_name: grafana
    ports:
    - 3000:3000
    environment:
    - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel
    user: "0"
    depends_on: [influxdb]
    volumes:
    - ./datasources:/etc/grafana/provisioning/datasources/
    - ./dashboards:/etc/grafana/provisioning/dashboards/

  chronograf:
    image: chronograf:1.8.8
    container_name: chronograf
    ports:
    - 8888:8888
    environment:
    - INFLUXDB_URL=http://influxdb:8086
    - KAPACITOR_URL=http://kapacitor:9092
    depends_on: [influxdb]

  kapacitor:
    image: kapacitor:1.5.8
    container_name: kapacitor
    ports:
    - 9092:9092
    environment:
    - KAPACITOR_HOSTNAME=kapacitor
    - KAPACITOR_LOGGING_LEVEL=INFO
    - KAPACITOR_REPORTING_ENABLED=false
    - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    depends_on: [influxdb]

  netdata:
    image: netdata/netdata:v1.29.3
    container_name: netdata
    ports:
    - 19999:19999
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add: [SYS_PTRACE]
    security_opt: [apparmor=unconfined]

  hddtemp:
    container_name: hddtemp
    image: drewster727/hddtemp-docker:latest
    privileged: true
    ports:
    - 7634:7634
    environment:
    - HDDTEMP_ARGS="-q -d -F /dev/sd*" \

  prometheus:
    image: prom/prometheus:v2.25.2
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  node-exporter:
    image: prom/node-exporter:v1.1.2
    container_name: node-exporter
    ports:
      - '9100:9100'
